baseURL: "https://fikrinhayati.com/"
title: Fikrin Hayatı
DefaultContentLanguage: "tr"
paginate: 99
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: G-D97060RCGM

minify:
    disableXML: true
    minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

sitemap:
  changefreq: "weekly"
  priority: 0.5
  filename: "sitemap.xml"

params:
    env: production
    title: Fikrin Hayatı
    description: "Fikrin Hayatı, hayata geçirilmiş olan fikirlerin, projelerin ve uygulamaların geliştirilme süreçlerini girişimciler ile paylaşan proje."
    keywords: [girişimcilik, blog, fikrin hayatı]
    author: Me
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2 January 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        disableFingerprinting: true
        favicon: /assets/favicon.ico
        favicon16x16: /assets/favicon-16x16.png
        favicon32x32: /assets/favicon-32x32.png
        apple_touch_icon: /assets/apple-touch-icon.png
        # safari_pinned_tab: "<link / abs url>"

    Images:
      maxSize: 2560
      setSizes:
        - 640
        - 960
        - 1280
        - 1920
        - 2560
      sizes: '(min-width: 1023px) 780px, (min-width: 675px) 620px, 100vw'

    profileMode:
        enabled: false
        title: Fikrin Hayatı
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Merhaba \U0001F44B"
        Content: Fikrin Hayatı, hayata geçirilmiş olan fikirlerin, projelerin ve uygulamaların geliştirilme süreçlerini girişimciler ile paylaşan proje. 

    socialIcons:
        - name: twitter
          url: "https://twitter.com/fikrinhayati"
        - name: github
          url: "https://github.com/mrabdullahsahin/fikrinhayati"
        - name: linkedin
          url: "https://linkedin.com/company/fikrin-hayati"

    cover:
        linkFullImages: true
        hidden: false

    editPost:
        URL: "https://github.com/mrabdullahsahin/fikrinhayati/blob/master/content"
        Text: "Değişiklik Öner"
        appendFilePath: true

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: tags
          name: Etiketler
          url: /tags/
          weight: 10